### PR TITLE
<PostCardListItem>

### PR DESCRIPTION
**Pull request by ryotogashi**

### CODE REVIEW

**Comment by ryotogashi** [comment]
Like Icon
Screen Shot 2020-03-15 at 2 37 15 AM

Dislike Icon
Screen Shot 2020-03-15 at 2 37 42 AM

Card
Screen Shot 2020-03-15 at 2 38 38 AM

PostCardListItem
Screen Shot 2020-03-15 at 2 38 05 AM

**Comment by ryotogashi** [comment]
Ready after #60

**Comment by ryotogashi** [comment]
@axross Can you check?

**Comment by axross** [comment]
Is this still going on? If the situation changed, please update in anyway (comment, update, move in the Kanban, etc).

**Comment by ryotogashi** [comment]
@axross Can you check?

I am still not so sure that files I put in models and utilities placed in right place. Please lecture me if you have any good ideas.

**Comment by ryotogashi** [comment]
#93

**Comment by axross** [comment]
@ryotogashi I guess you should close this pull request and open new one with organized commits

**Comment by ryotogashi** [comment]
@axross ok! I will

**Pull request closed without merging**
