### PR TITLE
Implement recent posts

### PR DESCRIPTION
**Pull request by ryotogashi**

### CODE REVIEW

**Comment by ryotogashi** [comment]
Screen Shot 2020-03-14 at 3 13 29 AM

**Comment by ryotogashi** [comment]
Screen Shot 2020-03-14 at 3 14 03 AM

**Comment by axross** [comment]
@ryotogashi Looks you set me as reviewer. Do you mean it's ready for a review?

**Comment by ryotogashi** [comment]
@axross Can you check?

**Comment by ryotogashi** [comment]
@axross Can you check?

**Comment by axross** [comment]
I'll close this for now. Even later, you can restore code here whenever you want.

**Pull request closed without merging**
