### PR TITLE
<PostCardList>

### PR DESCRIPTION
**Pull request by ryotogashi**
* add getStringWithSIMetricSuffix

* change map name by review.

### CODE REVIEW

**Comment by ryotogashi** [comment]
- [ ] getStringWithSIMetricSuffix
- [ ] getRelativeDateString
- [ ] getPositionByPlayerAndIndex
- [ ] calculateFinalPot
- [ ] PostCardListItem
- [ ] PostCardList

**Comment by ryotogashi** [comment]
This request is from #105

**Comment by ryotogashi** [comment]
@axross Can you check when you have time? I deleted getRelativeStringDate and use [date-fns](https://date-fns.org/)

**Comment by ryotogashi** [comment]
@axross Can you check when you have time? I deleted getRelativeStringDate and use [date-fns](https://date-fns.org/) and add loader.

**Comment by axross** [comment]
@ryotogashi Looks different stuff displayed. Is this okay?

**Pull request merged**
